<?php namespace pineapple;

class Configuration extends SystemModule
{
    public function route()
    {
        switch ($this->request->action) {
            case 'getCurrentTimeZone':
                $this->getCurrentTimeZone();
                break;
            case 'getLandingPageData':
                $this->getLandingPageData();
                break;
            case 'saveLandingPage':
                $this->saveLandingPageData();
                break;
            case 'changePass':
                $this->changePass();
                break;
            case 'changeTimeZone':
                $this->changeTimeZone();
                break;
            case 'resetPineapple':
                $this->resetPineapple();
                break;
            case 'haltPineapple':
                $this->haltPineapple();
                break;
            case 'rebootPineapple':
                $this->rebootPineapple();
                break;
            case 'getLandingPageStatus':
                $this->getLandingPageStatus();
                break;
            case 'getAutoStartStatus':
                $this->getAutoStartStatus();
                break;
            case 'enableLandingPage':
                $this->enableLandingPage();
                break;
            case 'disableLandingPage':
                $this->disableLandingPage();
                break;
            case 'enableAutoStart':
                $this->enableAutoStart();
                break;
            case 'disableAutoStart':
                $this->disableAutoStart();
                break;
            case 'getButtonScript':
                $this->getButtonScript();
                break;
            case 'saveButtonScript':
                $this->saveButtonScript();
                break;
            case 'getDevice':
                $this->getDeviceName();
                break;
            case 'getDeviceConfig':
                $this->getDeviceConfigArray();
                break;
            case 'getTorStatus':
                $this->getTorStatus();
                break;
            case 'getTorConfig':
                $this->getTorConfigResponse();
                break;
            case 'setTorEnabled':
                $this->setTorEnabled();
                break;
            case 'saveTorConfig':
                $this->saveTorConfig();
                break;
            case 'installTorPackage':
                $this->installTorPackage();
                break;
            case 'installObfs4Package':
                $this->installObfs4Package();
                break;
        }
    }

    // ------------------------------------------------------------------
    // Tor (obfs4) support toggle (#70)
    // ------------------------------------------------------------------

    private function torInstalled()
    {
        exec('opkg list-installed 2>/dev/null | grep -w tor', $out);
        return !empty($out);
    }

    private function obfs4Installed()
    {
        exec('opkg list-installed 2>/dev/null | grep -w obfs4', $out);
        return !empty($out);
    }

    private function torRunning()
    {
        return $this->checkRunningFull('/usr/bin/tor');
    }

    private function getTorStatus()
    {
        $this->response = array(
            'success' => true,
            'installed' => $this->torInstalled(),
            'running' => $this->torRunning(),
            'obfs4' => $this->obfs4Installed(),
            'enabled' => $this->torRunning(),
        );
    }

    private function writeTorrc($socksPort, $bridges, $useObfs4)
    {
        $torrc = "# generated by WiFi Pineapple panel\n";
        $torrc .= "SOCKSPort " . intval($socksPort) . "\n";
        $torrc .= "SOCKSPolicy accept 172.16.42.0/24\n";
        $torrc .= "SOCKSPolicy reject *\n";
        $torrc .= "Log notice file /tmp/tor.log\n";

        if ($useObfs4 && $this->obfs4Installed()) {
            $torrc .= "ClientTransportPlugin obfs4 exec /usr/bin/obfs4proxy managed\n";
        }

        $bridges = trim($bridges);
        if (!empty($bridges)) {
            $torrc .= "UseBridges 1\n";
            foreach (explode("\n", $bridges) as $bridge) {
                $bridge = trim($bridge);
                if (!empty($bridge)) {
                    $torrc .= "Bridge " . $bridge . "\n";
                }
            }
        }

        return file_put_contents('/etc/tor/torrc', $torrc) !== false;
    }

    private function getTorConfig()
    {
        $socksPort = 9050;
        $bridges = '';
        $useObfs4 = false;
        if (file_exists('/etc/tor/torrc')) {
            $lines = file('/etc/tor/torrc', FILE_IGNORE_NEW_LINES | FILE_SKIP_EMPTY_LINES);
            foreach ($lines as $line) {
                if (preg_match('/^SOCKSPort\s+(\d+)/', $line, $m)) {
                    $socksPort = intval($m[1]);
                }
                if (preg_match('/^Bridge\s+(.+)$/', $line, $m)) {
                    $bridges .= $m[1] . "\n";
                }
                if (strpos($line, 'ClientTransportPlugin obfs4') !== false) {
                    $useObfs4 = true;
                }
            }
        }
        return array('socksPort' => $socksPort, 'bridges' => trim($bridges), 'useObfs4' => $useObfs4);
    }

    private function getTorConfigResponse()
    {
        $config = array('socksPort' => 9050, 'bridges' => '', 'useObfs4' => false);
        if ($this->torInstalled()) {
            $config = $this->getTorConfig();
        }
        $this->response = array('success' => true, 'config' => $config);
    }

    private function setTorEnabled()
    {
        if (!$this->torInstalled()) {
            $this->error = 'Tor is not installed. Install it first.';
            return;
        }

        $enabled = !empty($this->request->enabled);
        if ($enabled) {
            if (!$this->torRunning()) {
                exec('/etc/init.d/tor enable 2>&1');
                exec('/etc/init.d/tor start 2>&1');
            }
        } else {
            exec('/etc/init.d/tor stop 2>&1');
            exec('/etc/init.d/tor disable 2>&1');
        }

        $this->response = array('success' => true, 'running' => $this->torRunning());
    }

    private function saveTorConfig()
    {
        if (!$this->torInstalled()) {
            $this->error = 'Tor is not installed. Install it first.';
            return;
        }

        $socksPort = isset($this->request->socksPort) ? intval($this->request->socksPort) : 9050;
        $bridges = isset($this->request->bridges) ? $this->request->bridges : '';
        $useObfs4 = !empty($this->request->useObfs4);

        if (!is_dir('/etc/tor')) {
            mkdir('/etc/tor', 0700, true);
        }

        if (!$this->writeTorrc($socksPort, $bridges, $useObfs4)) {
            $this->error = 'Could not write /etc/tor/torrc';
            return;
        }

        exec('/etc/init.d/tor restart 2>&1');
        $this->response = array('success' => true, 'running' => $this->torRunning());
    }

    private function installTorPackage()
    {
        $this->execBackground('opkg update && opkg install tor');
        $this->response = array('success' => true);
    }

    private function installObfs4Package()
    {
        $this->execBackground('opkg update && opkg install obfs4');
        $this->response = array('success' => true);
    }

    private function haltPineapple()
    {
        $this->execBackground("sync && led all off && halt");
        $this->response = array("success" => true);
    }

    private function rebootPineapple()
    {
        $this->execBackground("reboot");
        $this->response = array("success" => true);
    }

    private function resetPineapple()
    {
        $this->execBackground("jffs2reset -y && reboot &");
        $this->response = array("success" => true);
    }

    private function getCurrentTimeZone()
    {
        $currentTimeZone = exec('date +%Z%z');
        $this->response = array("currentTimeZone" => $currentTimeZone);
    }

    private function changeTimeZone()
    {
        $timeZone = $this->request->timeZone;
        file_put_contents('/etc/TZ', $timeZone);
        $this->uciSet('system.@system[0].timezone', $timeZone);
        $this->response = array("success" => true);
    }

    private function getLandingPageData()
    {
        $landingPage = file_get_contents('/etc/pineapple/landingpage.php');
        $this->response = array("landingPage" => $landingPage);
    }

    private function getLandingPageStatus()
    {
        if (!empty(exec("iptables -L -vt nat | grep 'www to:.*:80'"))) {
            $this->response = array("enabled" => true);
            return;
        }
        $this->response = array("enabled" => false);
    }

    private function enableLandingPage()
    {
        exec('iptables -t nat -A PREROUTING -p tcp --dport 80 -j DNAT --to-destination $(uci get network.lan.ipaddr):80');
        exec('iptables -t nat -A POSTROUTING -j MASQUERADE');
        copy('/pineapple/modules/Configuration/api/landingpage_index.php', '/www/index.php');
        $this->response = array("success" => true);
    }

    private function disableLandingPage()
    {
        @unlink('/www/index.php');
        exec('iptables -t nat -D PREROUTING -p tcp --dport 80 -j DNAT --to-destination $(uci get network.lan.ipaddr):80');
        $this->response = array("success" => true);
    }

    private function getAutoStartStatus()
    {
        if($this->uciGet("landingpage.@settings[0].autostart") == 1) {
            $this->response = array("enabled" => true);
        } else {
            $this->response = array("enabled" => false);
        }
    }

    private function enableAutoStart()
    {
        $this->uciSet("landingpage.@settings[0].autostart", "1");
        $this->response = array("success" => true);
    }

    private function disableAutoStart()
    {
        $this->uciSet("landingpage.@settings[0].autostart", "0");
        $this->response = array("success" => true);
    }

    private function saveLandingPageData()
    {
        if (file_put_contents('/etc/pineapple/landingpage.php', $this->request->landingPageData) !== false) {
            $this->response = array("success" => true);
        } else {
            $this->error = "Error saving Landing Page.";
        }
    }

    private function getButtonScript()
    {
        if (file_exists('/etc/pineapple/button_script')) {
            $script = file_get_contents('/etc/pineapple/button_script');
            $this->response = array("buttonScript" => $script);
        } else {
            $this->error = "The button script does not exist.";
        }
    }

    private function saveButtonScript()
    {
        if (file_exists('/etc/pineapple/button_script')) {
            file_put_contents('/etc/pineapple/button_script', $this->request->buttonScript);
            $this->response = array("success" => true);
        } else {
            $this->error = "The button script does not exist.";
        }
    }

    private function getDeviceName()
    {
        $this->response = array("device" => $this->getDevice());
    }

    private function getDeviceConfigArray()
    {
        $this->response = array("config" => $this->getDeviceConfig());
    }

    protected function changePass()
    {
        if ($this->request->newPassword === $this->request->newPasswordRepeat) {
            if (parent::changePassword($this->request->oldPassword, $this->request->newPassword) === true) {
                $this->response = array("success" => true);
                return;
            }
        }

        $this->response = array("success" => false);
    }
}